=== ahmed-hafsi/etalis/dEtalis/jtalis-distribute/scripts/XmlConfig.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:jxb="http://java.sun.com/xml/ns/jaxb" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.w3schools.com" elementFormDefault="qualified" targetNamespace="http://www.w3schools.com">

	<xs:element name="config" type="ConfigType" />

	<xs:complexType name="ConfigType">
		<xs:sequence>
			<xs:element name="debug" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="consult" type="ConsultFilesListType" minOccurs="0" maxOccurs="1" />
			<xs:element name="flags" type="EtalisFlagsListType" minOccurs="0" maxOccurs="1" />
			<xs:element name="predicates" type="PredicatesListType" minOccurs="0" maxOccurs="1" />
			<xs:element name="compileEventFiles" type="EventFilesListType" minOccurs="0" maxOccurs="1" />
			<xs:element name="eventTriggers" type="EventTriggersListType" minOccurs="0" maxOccurs="1" />
			<xs:element name="eventRules" type="EventRuleListType" minOccurs="0" maxOccurs="1" />
			<xs:element name="providers" type="ProviderListType" minOccurs="0" maxOccurs="1" />
			<xs:element name="outputQueues" type="OutputQueuesListType" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ConsultFilesListType">
		<xs:sequence>
			<xs:element name="file" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="EtalisFlagsListType">
		<xs:sequence>
			<xs:element name="flag" type="EtalisFlagType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="PredicatesListType">
		<xs:sequence>
			<xs:element name="predicate" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="EventFilesListType">
		<xs:sequence>
			<xs:element name="file" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="EventTriggersListType">
		<xs:sequence>
			<xs:element name="trigger" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="EtalisFlagType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="value" type="xs:string" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="OutputQueuesListType">
		<xs:sequence>
			<xs:element name="queue" type="OutputQueueType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="OutputQueueType">
		<xs:sequence>
			<xs:element name="providers" type="ProviderListType" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="regex" type="xs:string" use="optional" />
	</xs:complexType>

	<xs:complexType name="EventRuleListType">
		<xs:sequence>
			<xs:element name="eventRule" type="EventRuleType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="EventRuleType">
		<xs:all>
			<xs:element name="consequence" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="antecedent" type="xs:string" minOccurs="1" maxOccurs="1" />
		</xs:all>
		<xs:attribute name="ruleId" type="xs:string" use="optional" />
	</xs:complexType>

	<xs:complexType name="ProviderListType">
		<xs:sequence>
			<xs:element name="provider" type="ProviderType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ProviderType">
		<xs:sequence minOccurs="0">
			<xs:element name="parameters" type="ParameterListType" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="regex" type="xs:string" use="optional" />
		<xs:attribute name="class" type="xs:string" use="required" />
		<xs:attribute name="feedDelay" type="xs:long" use="optional" />
		<xs:attribute name="type" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="input" />
					<xs:enumeration value="output" />
					<xs:enumeration value="both" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>

	</xs:complexType>

	<xs:complexType name="ParameterListType">
		<xs:sequence>
			<xs:element name="parameter" type="ParameterType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ParameterType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

</xs:schema>

=== ahmed-hafsi/etalis/dEtalis/jtalis-distribute/resources/simple-server.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xsi:schemaLocation="http://www.w3schools.com http://etalis.googlecode.com/files/XmlConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3schools.com">

	<eventTriggers>
		<trigger>_/_</trigger>
	</eventTriggers>

	<eventRules>
		<eventRule>
			<consequence>c</consequence>
			<antecedent>a seq b</antecedent>
		</eventRule>
	</eventRules>

	<providers>
		<provider type="input" class="com.jtalis.core.event.provider.DefaultInputProvider" />
		<provider regex="c" type="output" class="com.jtalis.core.event.provider.DefaultOutputProvider">
			<parameters>
				<parameter name="url">localhost:8888</parameter>
			</parameters>
		</provider>
		<provider type="output" class="com.jtalis.core.event.provider.DefaultOutputProvider" />
	</providers>

</config>

=== ahmed-hafsi/etalis/dEtalis/jtalis-distribute/resources/simple-client.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xsi:schemaLocation="http://www.w3schools.com http://etalis.googlecode.com/files/XmlConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3schools.com">

	<eventTriggers>
		<trigger>_/_</trigger>
	</eventTriggers>

	<eventRules>
		<eventRule>
			<consequence>e</consequence>
			<antecedent>c seq d</antecedent>
		</eventRule>
	</eventRules>

	<providers>
		<provider type="input" class="com.jtalis.core.event.provider.DefaultInputProvider" />
		<provider type="input" class="com.jtalis.core.event.provider.DefaultInputProvider">
			<parameters>
				<parameter name="url">localhost:8888</parameter>
				<parameter name="restoreConnection">true</parameter>
			</parameters>
		</provider>
		<provider type="output" class="com.jtalis.core.event.provider.DefaultOutputProvider" />
	</providers>

</config>

=== ahmed-hafsi/etalis/jtalis/jtalis-core/resources/basic-run-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xsi:schemaLocation="http://www.w3schools.com http://etalis.googlecode.com/files/XmlConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3schools.com">

	<debug>false</debug>

	<eventTriggers>
		<trigger>_/_</trigger>
	</eventTriggers>

	<eventRules>
		<eventRule>
			<consequence>c(X)</consequence>
			<antecedent>a(X) seq b(X)</antecedent>
		</eventRule>
		<eventRule>
			<consequence>c</consequence>
			<antecedent>a seq b</antecedent>
		</eventRule>
	</eventRules>

	<providers>
		<provider type="input" class="com.jtalis.core.event.provider.DefaultInputProvider" feedDelay="1000" />
		<provider regex="c" type="output" class="com.jtalis.core.event.provider.DefaultOutputProvider" />
	</providers>

</config>

=== ahmed-hafsi/etalis/jtalis/jtalis-activemq/src/main/resources/amq-ruleid-run.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xsi:schemaLocation="http://www.w3schools.com http://etalis.googlecode.com/files/XmlConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3schools.com">

	<flags>
		<flag>
			<name>save_ruleId</name>
			<value>on</value>
		</flag>
	</flags>

	<eventTriggers>
		<trigger>_/_</trigger>
	</eventTriggers>

	<compileEventFiles>
		<file>rule01.event</file>
	</compileEventFiles>

	<providers>
		<provider type="input" class="com.jtalis.activemq.ActiveMQInputProvider">
			<parameters>
				<parameter name="url">tcp://localhost:61616</parameter>
				<parameter name="topic">JtalisInputEvent</parameter>
			</parameters>
		</provider>
		
		<provider regex="a|b" type="output" class="com.jtalis.activemq.ActiveMQXMLOutputProvider">
			<parameters>
				<parameter name="url">tcp://localhost:61616</parameter>
				<parameter name="topic">JtalisAtomicEvent</parameter>
			</parameters>
		</provider>
		
		<provider regex="c" type="output" class="com.jtalis.activemq.ActiveMQXMLOutputProvider">
			<parameters>
				<parameter name="url">tcp://localhost:61616</parameter>
				<parameter name="topic">JtalisComplexEvent</parameter>
			</parameters>
		</provider>

	</providers>

</config>

=== ahmed-hafsi/etalis/jtalis/jtalis-activemq/src/main/resources/activemq-run-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xsi:schemaLocation="http://www.w3schools.com http://etalis.googlecode.com/files/XmlConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3schools.com">

	<eventTriggers>
		<trigger>_/_</trigger>
	</eventTriggers>

	<eventRules>
		<eventRule>
			<consequence>c(X, Y)</consequence>
			<antecedent>a(X, _) seq b(Y, _)</antecedent>
		</eventRule>
	</eventRules>

	<providers>
		<provider type="input" class="com.jtalis.activemq.ActiveMQInputProvider">
			<parameters>
				<parameter name="url">tcp://localhost:61616</parameter>
				<parameter name="topic">JtalisInputEvent</parameter>
			</parameters>
		</provider>
		
		<provider regex="c" type="output" class="com.jtalis.activemq.ActiveMQOutputProvider">
			<parameters>
				<parameter name="url">tcp://localhost:61616</parameter>
				<parameter name="topic">JtalisFiredEvent</parameter>
			</parameters>
		</provider>
		<provider  type="output" class="com.jtalis.core.event.provider.DefaultOutputProvider">
		</provider>
	</providers>

</config>

=== ahmed-hafsi/etalis/jtalis/jtalis-jdbc/src/main/resources/jdbc-run-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xsi:schemaLocation="http://www.w3schools.com http://etalis.googlecode.com/files/XmlConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3schools.com">
	<flags>
		<flag>
			<name>save_ruleId</name>
			<value>on</value>
		</flag>
	</flags>
	<eventTriggers>
		<trigger>_/_</trigger>
	</eventTriggers>

	
	<compileEventFiles>
		<file>test_01.event</file>
	</compileEventFiles>

	<providers>
		<provider type="input" class="com.jtalis.core.event.provider.DefaultInputProvider" >
			<parameters>
				<parameter name="file">eventstream_2_1.P</parameter>
			</parameters>
		</provider>
		<provider  type="output" class="com.jtalis.jdbc.JDBCOutputProvider">
			<parameters>
				<parameter name="bufferSize">0</parameter>
				<parameter name="url">jdbc:h2:file:~/all-events</parameter>
				<parameter name="user">sa</parameter>
				<parameter name="password"></parameter>
			</parameters>
		</provider>

	</providers>

</config>

=== ahmed-hafsi/etalis/jtalis/jtalis-activemq/src/main/resources/test-xml-outputprovider.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xsi:schemaLocation="http://www.w3schools.com http://etalis.googlecode.com/files/XmlConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3schools.com">
	<eventTriggers>
		<trigger>_/_</trigger>
	</eventTriggers>

	<eventRules>
		<eventRule>
			<consequence>c(X)</consequence>
			<antecedent>a(X) seq b(Y)</antecedent>
		</eventRule>
	</eventRules>

	<providers>
		<provider  type="input" class="com.jtalis.core.event.provider.DefaultInputProvider">
		</provider>
		<provider  type="output" class="com.jtalis.core.event.provider.XMLOutputProvider">
			<parameters>
				<parameter name="file">log-xml.event</parameter>
				<parameter name="xsd">SimpleEventSchema.xsd</parameter>
			</parameters>
		</provider>
	</providers>

</config>
